language: java

jdk:
  - openjdk11

# whitelist
branches:
  only:
    - master
    - davidc
    - michaelL
    - kevinK
    - teamDev
after_success:
  - mvn clean test jacoco:report coveralls:report
